In [1]:
'''
# This code downloads the file from a url

import requests
url = 'https://www.kaggle.com/datasets/salvatorerastelli/spotify-and-youtube/download?datasetVersionNumber=2'
r = requests.get(url)
file_extension = '.csv'
uncleaned_dataset = '{url}'

with open(uncleaned_dataset, 'wb') as f:
   f.write(r.content)
'''

"\n# This code downloads the file from a url\n\nimport requests\nurl = 'https://www.kaggle.com/datasets/salvatorerastelli/spotify-and-youtube/download?datasetVersionNumber=2'\nr = requests.get(url)\nfile_extension = '.csv'\nuncleaned_dataset = '{url}'\n\nwith open(uncleaned_dataset, 'wb') as f:\n   f.write(r.content)\n"

In [2]:
import pandas as pd
import numpy as np

# Read the CSV file
data = pd.read_csv('uncleaned_dataset.csv')

# Print the first few rows
# print(data.head())

# Get the column names
column_names = data.columns
#column_names

len(data)

20718

In [3]:
data.dropna(inplace=True)
len(data)

19170

In [4]:
selected_columns = ['Artist', 
                    'Track', 
                    'Album', 
                    'Album_type', 
                    'Danceability', 
                    'Energy', 
                    'Key', 
                    'Loudness', 
                    'Speechiness', 
                    'Acousticness', 
                    'Instrumentalness', 
                    'Liveness', 
                    'Valence', 
                    'Tempo', 
                    'Duration_ms',
                    'Stream',
                    'Views', 
                    'Likes', 
                    'Comments', 
                    'official_video']
subsetDeletedColumns = data[selected_columns]
subsetDeletedColumns.head()

,Artist,Track,Album,Album_type,Danceability,Energy,Key,Loudness,Speechiness,Acousticness,Instrumentalness,Liveness,Valence,Tempo,Duration_ms,Stream,Views,Likes,Comments,official_video
0,Gorillaz,Feel Good Inc.,Demon Days,album,0.818,0.705,6.0,-6.679,0.1770,0.008360,0.002330,0.6130,0.772,138.559,222640.0,1.040235e+09,693555221.0,6220896.0,169907.0,True
1,Gorillaz,Rhinestone Eyes,Plastic Beach,album,0.676,0.703,8.0,-5.815,0.0302,0.086900,0.000687,0.0463,0.852,92.761,200173.0,3.100837e+08,72011645.0,1079128.0,31003.0,True
2,Gorillaz,New Gold (feat. Tame Impala and Bootie Brown),New Gold (feat. Tame Impala and Bootie Brown),single,0.695,0.923,1.0,-3.930,0.0522,0.042500,0.046900,0.1160,0.551,108.014,215150.0,6.306347e+07,8435055.0,282142.0,7399.0,True
3,Gorillaz,On Melancholy Hill,Plastic Beach,album,0.689,0.739,2.0,-5.810,0.0260,0.000015,0.509000,0.0640,0.578,120.423,233867.0,4.346636e+08,211754952.0,1788577.0,55229.0,True
4,Gorillaz,Clint Eastwood,Gorillaz,album,0.663,0.694,10.0,-8.627,0.1710,0.025300,0.000000,0.0698,0.525,167.953,340920.0,6.172597e+08,618480958.0,6197318.0,155930.0,True

In [5]:
renameColumns = {'Stream': 'SpotifyStream',
                 'Views': 'YoutubeViews',
                 'official_video': 'OfficialVideo'
                }
mainDataset = subsetDeletedColumns.rename(columns=renameColumns)
mainDataset.head()

,Artist,Track,Album,Album_type,Danceability,Energy,Key,Loudness,Speechiness,Acousticness,Instrumentalness,Liveness,Valence,Tempo,Duration_ms,SpotifyStream,YoutubeViews,Likes,Comments,OfficialVideo
0,Gorillaz,Feel Good Inc.,Demon Days,album,0.818,0.705,6.0,-6.679,0.1770,0.008360,0.002330,0.6130,0.772,138.559,222640.0,1.040235e+09,693555221.0,6220896.0,169907.0,True
1,Gorillaz,Rhinestone Eyes,Plastic Beach,album,0.676,0.703,8.0,-5.815,0.0302,0.086900,0.000687,0.0463,0.852,92.761,200173.0,3.100837e+08,72011645.0,1079128.0,31003.0,True
2,Gorillaz,New Gold (feat. Tame Impala and Bootie Brown),New Gold (feat. Tame Impala and Bootie Brown),single,0.695,0.923,1.0,-3.930,0.0522,0.042500,0.046900,0.1160,0.551,108.014,215150.0,6.306347e+07,8435055.0,282142.0,7399.0,True
3,Gorillaz,On Melancholy Hill,Plastic Beach,album,0.689,0.739,2.0,-5.810,0.0260,0.000015,0.509000,0.0640,0.578,120.423,233867.0,4.346636e+08,211754952.0,1788577.0,55229.0,True
4,Gorillaz,Clint Eastwood,Gorillaz,album,0.663,0.694,10.0,-8.627,0.1710,0.025300,0.000000,0.0698,0.525,167.953,340920.0,6.172597e+08,618480958.0,6197318.0,155930.0,True

In [6]:
# Filter for values not equal to "album" or "single" in the "Album_type" column
filtered_data = mainDataset[~mainDataset['Album_type'].isin(['album', 'single', 'compilation'])]

# Print the filtered data
print(filtered_data['Album_type'])

Series([], Name: Album_type, dtype: object)

In [7]:
# Replace values in the "Album_type" column
replacement_mapping = {'single': 1, 'album': 2, 'compilation': 3}
mainDataset['Album_type'] = mainDataset['Album_type'].replace(replacement_mapping)
mainDataset.head()

,Artist,Track,Album,Album_type,Danceability,Energy,Key,Loudness,Speechiness,Acousticness,Instrumentalness,Liveness,Valence,Tempo,Duration_ms,SpotifyStream,YoutubeViews,Likes,Comments,OfficialVideo
0,Gorillaz,Feel Good Inc.,Demon Days,2,0.818,0.705,6.0,-6.679,0.1770,0.008360,0.002330,0.6130,0.772,138.559,222640.0,1.040235e+09,693555221.0,6220896.0,169907.0,True
1,Gorillaz,Rhinestone Eyes,Plastic Beach,2,0.676,0.703,8.0,-5.815,0.0302,0.086900,0.000687,0.0463,0.852,92.761,200173.0,3.100837e+08,72011645.0,1079128.0,31003.0,True
2,Gorillaz,New Gold (feat. Tame Impala and Bootie Brown),New Gold (feat. Tame Impala and Bootie Brown),1,0.695,0.923,1.0,-3.930,0.0522,0.042500,0.046900,0.1160,0.551,108.014,215150.0,6.306347e+07,8435055.0,282142.0,7399.0,True
3,Gorillaz,On Melancholy Hill,Plastic Beach,2,0.689,0.739,2.0,-5.810,0.0260,0.000015,0.509000,0.0640,0.578,120.423,233867.0,4.346636e+08,211754952.0,1788577.0,55229.0,True
4,Gorillaz,Clint Eastwood,Gorillaz,2,0.663,0.694,10.0,-8.627,0.1710,0.025300,0.000000,0.0698,0.525,167.953,340920.0,6.172597e+08,618480958.0,6197318.0,155930.0,True

In [8]:
# Define the columns to find the range for
columns_to_check = ['Danceability', 'Energy', 'Key', 'Loudness', 'Speechiness',
                    'Acousticness', 'Instrumentalness', 'Liveness', 'Valence', 'Tempo']

# Find the range of values for each column
for column_name in columns_to_check:
    column_min = mainDataset[column_name].min()
    column_max = mainDataset[column_name].max()
    print(f"The range of values in the {column_name} column is from {column_min} to {column_max}.")

The range of values in the Danceability column is from 0.0 to 0.975.
The range of values in the Energy column is from 2.03e-05 to 1.0.
The range of values in the Key column is from 0.0 to 11.0.
The range of values in the Loudness column is from -46.251 to 0.92.
The range of values in the Speechiness column is from 0.0 to 0.964.
The range of values in the Acousticness column is from 1.11e-06 to 0.996.
The range of values in the Instrumentalness column is from 0.0 to 1.0.
The range of values in the Liveness column is from 0.0145 to 1.0.
The range of values in the Valence column is from 0.0 to 0.993.
The range of values in the Tempo column is from 0.0 to 243.372.

In [9]:
# Define the columns to check
columns_to_check = ['Danceability', 'Energy', 'Key', 'Loudness', 'Speechiness',
                    'Acousticness', 'Instrumentalness', 'Liveness', 'Valence', 'Tempo']

# Filter values below 0 for each column
for column_name in columns_to_check:
    values_below_zero = mainDataset[mainDataset[column_name] < 0][column_name]
    print(f"Values below 0 in {column_name}:")
    print(values_below_zero)
    print()

Values below 0 in Danceability:
Series([], Name: Danceability, dtype: float64)

Values below 0 in Energy:
Series([], Name: Energy, dtype: float64)

Values below 0 in Key:
Series([], Name: Key, dtype: float64)

Values below 0 in Loudness:
0       -6.679
1       -5.815
2       -3.930
3       -5.810
4       -8.627
         ...
20713   -6.344
20714   -1.786
20715   -4.679
20716   -4.004
20717   -4.543
Name: Loudness, Length: 19164, dtype: float64

Values below 0 in Speechiness:
Series([], Name: Speechiness, dtype: float64)

Values below 0 in Acousticness:
Series([], Name: Acousticness, dtype: float64)

Values below 0 in Instrumentalness:
Series([], Name: Instrumentalness, dtype: float64)

Values below 0 in Liveness:
Series([], Name: Liveness, dtype: float64)

Values below 0 in Valence:
Series([], Name: Valence, dtype: float64)

Values below 0 in Tempo:
Series([], Name: Tempo, dtype: float64)

In [10]:
# Define the column name
column_name = 'OfficialVideo'
# Replace values in the column
mainDataset[column_name].replace({True: 1, False: 0}, inplace=True)
mainDataset

,Artist,Track,Album,Album_type,Danceability,Energy,Key,Loudness,Speechiness,Acousticness,Instrumentalness,Liveness,Valence,Tempo,Duration_ms,SpotifyStream,YoutubeViews,Likes,Comments,OfficialVideo
0,Gorillaz,Feel Good Inc.,Demon Days,2,0.818,0.705,6.0,-6.679,0.1770,0.008360,0.002330,0.6130,0.7720,138.559,222640.0,1.040235e+09,693555221.0,6220896.0,169907.0,1
1,Gorillaz,Rhinestone Eyes,Plastic Beach,2,0.676,0.703,8.0,-5.815,0.0302,0.086900,0.000687,0.0463,0.8520,92.761,200173.0,3.100837e+08,72011645.0,1079128.0,31003.0,1
2,Gorillaz,New Gold (feat. Tame Impala and Bootie Brown),New Gold (feat. Tame Impala and Bootie Brown),1,0.695,0.923,1.0,-3.930,0.0522,0.042500,0.046900,0.1160,0.5510,108.014,215150.0,6.306347e+07,8435055.0,282142.0,7399.0,1
3,Gorillaz,On Melancholy Hill,Plastic Beach,2,0.689,0.739,2.0,-5.810,0.0260,0.000015,0.509000,0.0640,0.5780,120.423,233867.0,4.346636e+08,211754952.0,1788577.0,55229.0,1
4,Gorillaz,Clint Eastwood,Gorillaz,2,0.663,0.694,10.0,-8.627,0.1710,0.025300,0.000000,0.0698,0.5250,167.953,340920.0,6.172597e+08,618480958.0,6197318.0,155930.0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20713,SICK LEGEND,JUST DANCE HARDSTYLE,JUST DANCE HARDSTYLE,1,0.582,0.926,5.0,-6.344,0.0328,0.448000,0.000000,0.0839,0.6580,90.002,94667.0,9.227144e+06,71678.0,1113.0,0.0,1
20714,SICK LEGEND,SET FIRE TO THE RAIN HARDSTYLE,SET FIRE TO THE RAIN HARDSTYLE,1,0.531,0.936,4.0,-1.786,0.1370,0.028000,0.000000,0.0923,0.6570,174.869,150857.0,1.089818e+07,164741.0,2019.0,0.0,1
20715,SICK LEGEND,OUTSIDE HARDSTYLE SPED UP,OUTSIDE HARDSTYLE SPED UP,1,0.443,0.830,4.0,-4.679,0.0647,0.024300,0.000000,0.1540,0.4190,168.388,136842.0,6.226110e+06,35646.0,329.0,0.0,1
20716,SICK LEGEND,ONLY GIRL HARDSTYLE,ONLY GIRL HARDSTYLE,1,0.417,0.767,9.0,-4.004,0.4190,0.356000,0.018400,0.1080,0.5390,155.378,108387.0,6.873961e+06,6533.0,88.0,0.0,1
20717,SICK LEGEND,MISS YOU HARDSTYLE,MISS YOU HARDSTYLE,1,0.498,0.938,6.0,-4.543,0.1070,0.002770,0.911000,0.1360,0.0787,160.067,181500.0,5.695584e+06,158697.0,2484.0,0.0,1

In [11]:
# Assuming 'mainDataset' is your DataFrame

# Specify the columns that may contain numbers in scientific notation
columns_to_convert = ['Danceability', 'Energy', 'Key', 'Loudness', 'Speechiness',
                      'Acousticness', 'Instrumentalness', 'Liveness', 'Valence',
                      'Tempo', 'Duration_ms', 'YoutubeViews', 'SpotifyStream', 'Likes', 'Comments']

# Convert scientific notation to decimal format for the specified columns
mainDataset[columns_to_convert] = mainDataset[columns_to_convert].apply(pd.to_numeric, errors='coerce')

In [12]:
import psycopg2
conn = psycopg2.connect(host="database-bi-project.cayammbzicyq.us-east-1.rds.amazonaws.com",
                       port=5432,
                       user="postgres",
                       password="Utumno03Melkor"
                       )

In [13]:
conn.autocommit=True

In [14]:
# SQL script to drop and create the table
db_create_query = """
    DROP TABLE IF EXISTS spotifydata;
    CREATE TABLE spotifydata (
        Artist VARCHAR,
        Track VARCHAR,
        Album VARCHAR,
        Album_type NUMERIC,
        Danceability NUMERIC,
        Energy NUMERIC,
        Key NUMERIC,
        Loudness NUMERIC,
        Speechiness NUMERIC,
        Acousticness NUMERIC,
        Instrumentalness NUMERIC,
        Liveness NUMERIC,
        Valence NUMERIC,
        Tempo NUMERIC,
        Duration_ms NUMERIC,
        SpotifyStream NUMERIC,
        YoutubeViews NUMERIC,
        Likes NUMERIC,
        Comments NUMERIC,
        OfficialVideo NUMERIC
    );
"""

# Create a cursor object
cursor = conn.cursor()

# Execute the table creation script
cursor.execute(db_create_query)

In [ ]:
# Iterate over each row in the DataFrame and insert into the table
for _, row in mainDataset.iterrows():
    insert_query = """
        INSERT INTO spotifydata (
            Artist, Track, Album, Album_type, Danceability, Energy,
            Key, Loudness, Speechiness, Acousticness, Instrumentalness,
            Liveness, Valence, Tempo, Duration_ms, SpotifyStream,
            YoutubeViews, Likes, Comments, OfficialVideo
        ) VALUES (
            %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s
        )
    """
    values = tuple(row.values)  # Convert the row values to a tuple
    cursor.execute(insert_query, values)

# Close the cursor and connection
cursor.close()
conn.close()

In [17]:
# Read the CSV file
dataCountry = pd.read_csv('country_uncleaned_dataset.csv')

# Print the first few rows
# print(data.head())

# Get the column names
column_names = dataCountry.columns
# print(column_names)

In [18]:
selected_columns = ['Country', 
                    'Continent', 
                    'Rank', 
                    'Title', 
                    'Artists', 
                    'Album', 
                    'Explicit']
dataCountry = dataCountry[selected_columns]
# dataCountry.head()

In [27]:
import psycopg2
conn = psycopg2.connect(host="database-bi-project.cayammbzicyq.us-east-1.rds.amazonaws.com",
                       port=5432,
                       user="postgres",
                       password="Utumno03Melkor"
                       )

conn.autocommit=True

# SQL script to drop and create the table
db_create_query = """
    DROP TABLE IF EXISTS countrydata;
    CREATE TABLE countrydata (
        Country VARCHAR,
        Continent VARCHAR,
        Rank NUMERIC,
        Title VARCHAR,
        Artists VARCHAR,
        Album VARCHAR,
        Explicit NUMERIC
    );
"""

# Create a cursor object
cursor = conn.cursor()

# Execute the table creation script
cursor.execute(db_create_query)

In [28]:
# Iterate over each row in the DataFrame and insert into the table
for _, row in dataCountry.iterrows():
    insert_query = """
        INSERT INTO countrydata (
            Country, Continent, Rank, Title, Artists, Album, Explicit
        ) VALUES (
            %s, %s, %s, %s, %s, %s, %s
        )
    """
    values = tuple(row.values)  # Convert the row values to a tuple
    cursor.execute(insert_query, values)

# Close the cursor and connection
cursor.close()
conn.close()